# Generated by Django 4.1.1 on 2022-09-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="자산그룹명")),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("name", models.CharField(max_length=30, verbose_name="자산그룹명")),
                (
                    "current_price",
                    models.PositiveIntegerField(default=0, verbose_name="현재가"),
                ),
                (
                    "isin",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISIN",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=40, verbose_name="계좌명")),
                ("account_num", models.PositiveBigIntegerField(verbose_name="계좌번호")),
                (
                    "starting_fund",
                    models.PositiveBigIntegerField(default=0, verbose_name="투자원금"),
                ),
                (
                    "total_asset",
                    models.PositiveBigIntegerField(default=0, verbose_name="계좌 총 자산"),
                ),
                ("cur_price", models.PositiveBigIntegerField(verbose_name="현재가")),
                ("order", models.PositiveIntegerField(verbose_name="보유수량")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment.bank",
                    ),
                ),
                (
                    "isin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=40, verbose_name="계좌명")),
                ("account_num", models.IntegerField(verbose_name="계좌번호")),
                ("starting_fund", models.IntegerField(default=0, verbose_name="투자원금")),
                ("total_asset", models.IntegerField(default=0, verbose_name="계좌 총 자산")),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investment.bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
